CREATE DATABASE QuanLyCuaHangQuanAo
USE QuanLyCuaHangQuanAo

CREATE TABLE ChiTietHoaDonBan(
MaHDBan NCHAR(20) not null,
MaHang NCHAR(20) not null,
SoLuong INT NULL,
DonGia INT NULL,
GiamGia FLOAT NULL,
ThanhTien FLOAT NULL,
PRIMARY KEY (MaHDBan,MaHang)
)

CREATE TABLE HoaDonBan(
MaHDBan NCHAR(20) NOT NULL PRIMARY KEY,
MaNhanVien NCHAR(20) NOT NULL,
MaKhach NCHAR(20) NOT NULL,
NgayBan DATETIME NULL,
TongTien FLOAT NULL,
)
CREATE TABLE Khach (
MaKhach NCHAR(20) NOT NULL PRIMARY KEY,
TenKhach NVARCHAR(50) NULL,
DiaChi NVARCHAR(50) NULL,
DienThoai NVARCHAR(50) NULL,
)
CREATE TABLE NhanVien(
MaNhanVien NCHAR(20) NOT NULL PRIMARY KEY,
TenNhanVien NVARCHAR(50) NULL,
GioiTinh NVARCHAR(50) NULL,
NgaySinh DATETIME NULL,
DiaChi NVARCHAR(50) NULL,
DienThoai NVARCHAR(50) NULL,
)
CREATE TABLE Hang(
MaHang NCHAR(20) NOT NULL PRIMARY KEY,
TenHang NVARCHAR(50) NOT NULL,
SoLuong FLOAT (53) NOT NULL,
DonGiaNhap 	FLOAT (53) NOT NULL,
DonGiaBan	FLOAT (53) NOT NULL,
Anh 	NVARCHAR(200) NOT NULL,
GhiChu 	 NVARCHAR(200)  NULL
)
